export const ActionType = {
    GET_COINGECKO_DATA : 'GET_COINGECKO_DATA',
    SUCCESS_COINGECKO_DATA : 'SUCCESS_COINGECKO_DATA',
    FAILED_COINGECKO_DATA : 'FAILED_COINGECKO_DATA',
    FILTER_COINGECKO_DATA: 'FILTER_COINGECKO_DATA'
};
